config/routes.rb
SoundcloudSocial::Application.routes.draw do
  get "listen/show"

  get "home/index"

  resources :socky do
    collection do
      post :subscribe
      post :unsubscribe
      post :message
      post :start
      post :pause
      post :reset
      post :login
      post :logout
    end
  end

  controller :listen do
    match "/:userpermalink/:trackpermalink" => "listen#show"
  end

  root :to => "home#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/listen_controller.rb
require 'net/http'

class ListenController < ApplicationController
  def show 
    @userpermalink = params[:userpermalink] 
    @trackpermalink =  params[:trackpermalink]
=begin
    # resolve url
    resolver_url = 'http://api.soundcloud.com/resolve?url='
    original_url = 'http://soundcloud.com/' + params[:userpermalink] + '/' + params[:trackpermalink]
    url = resolver_url + original_url
    puts url
    response = Net::HTTP.get_response(URI.parse(url))
    puts response
    if response.is_a? Net::HTTPRedirection
      puts response['location']
      @trackurl = response['location']
    end
=end
  end

end

app/controllers/socky_controller.rb
require 'json'

class SockyController < ApplicationController

  skip_before_filter :verify_authenticity_token

  # This has no effect on client side
  def subscribe
    Socky.send( {:action => "subscribe",
                 :channel => params[:channel],
                 :client => (params[:client_id] || '')}.to_json)
    render :text => "ok"
  end

  def unsubscribe
    Socky.send( {:action => "unsubscribe",
                 :channel => params[:channel],
                 :user => (params[:client_id] || '')}.to_json)
    render :text => "ok"
  end

  # Performed when user has chosen username
  def login
    Socky.send( {:action  => "login", 
                 :user    => params[:user],
                 :channel => params[:channel]}.to_json,
               :to => { :channels => params[:channel] })
  render :text => "ok"
  end

  def logout
    Socky.send( {:action  => "logout", 
                 :user    => params[:user],
                 :channel => params[:channel]}.to_json,
               :to => { :channels => params[:channel] })
  render :text => "ok"
  end


  def message
    Socky.send( {:action  => "message",
                 :client  => (params[:client_id] || ''),
                 :user    => params[:user],
                 :channel => params[:channel],
                 :message => params[:message]}.to_json,
                :to => { :channels => params[:channel] })
    render :text => "ok"
  end

  def start
    Socky.send( {:action  => "start", 
                 :channel => params[:channel],
                 :client  => (params[:client_id] || ''),
                 :postion => (params[:position] || '')}.to_json,
                :to => { :channels => params[:channel] })
    render :text => "ok"
  end

  def pause
    Socky.send( {:action => "pause",
                 :channel => params[:channel],
                 :client => (params[:client_id] || '')}.to_json,
                :to => { :channels => params[:channel] })
    render :text => "ok"
  end

  def reset
    Socky.send( {:action => "reset",
                 :client => (params[:client_id] || '')}.to_json)
    render :text => "ok"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listen_helper.rb
module ListenHelper
end

app/views/home/index.html.haml
= javascript_include_tag "home"
  
#header
  %a#logo{:href => '/'}
#enter-sc-url
  %h2 Paste your SoundCloud track url here
  %input{:type => "text", :id => "sc_url"}
    %p.small Should look like http://soundcloud.com/username/track-name

#example-tracks
  %h3 If you just want to test SoundCloud Social, join one of these tracks:
  %p 
    %a{:href => "/snoopdoggmusic/02-i-wanna-rock"}Snoop Dog - I Wanna Rock
  %p 
    %a{:href => "/warp-records/brian-eno-2-forms-of-anger-small-craft-on-a-milk-sea"}Brian Eno - 2 Forms Of Anger Rock
  %p
    %a{:href => "/imogenheap/first-train-home"}Imogen Heap - First Train Home

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title SoundcloudSocial
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Lobster:regular&subset=latin'
    = stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'compiled/print.css', :media => 'print'
    /[if IE]
      = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
    -#= stylesheet_link_tag :all
    = javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"
    = javascript_include_tag "rails", "application"
    = csrf_meta_tag
  %body
    .container
      .two-col
        #content
          = yield
        #footer
          %a#about If you dont get it, click here! (FAQ and About)

    #about-box
      %a#close.close X
      %h1 SoundCloud Social
      %h2 Listen and Chat together
      %h3
        On
        %strong SoundCloud Social
        you can
        %strong listen
        to
        %a{:href => "http://soundcloud.com"}SoundCloud
        tracks together and chat in realtime about it.
      #built-by
        %p
          Built by
          %a{:href => "http://www.freenerd.de"}Johan Uhle
          after the idea by and help of
          %a{:href => "http://twitter.com/nils_westerlund"} Nils Westerlund
        %p
          Major parts have been written at the
          %a{:href => "http://bcn.musichackday.org/"} Music Hack Day Barcelona
          in autumn 2010.
        %p
          If you want to learn more about the project,
          %a{:href => "http://www.twitter.com/souncloudsocial"}
            %strong follow us on Twitter
          and check the
          %a{:href => "http://github.com/freenerd/soundcloud-social/"}repository on GitHub

app/views/listen/show.html.haml
- message_method_url = url_for(:controller => "socky", :action => "message")
- start_url = url_for(:controller => "socky", :action => "start")
- pause_url = url_for(:controller => "socky", :action => "pause")
- reset_url = url_for(:controller => "socky", :action => "reset")
- login_url = url_for(:controller => "socky", :action => "login")
- logout_url = url_for(:controller => "socky", :action => "logout")
- channel = @userpermalink + '/' + @trackpermalink

:javascript
  var message_method_url = '#{message_method_url}';
  var start_url = '#{start_url}';
  var pause_url = '#{pause_url}';
  var reset_url = '#{reset_url}';
  var login_url = '#{login_url}';
  var logout_url = '#{logout_url}';
  var channel = '#{channel}';

= javascript_include_tag :socky
- random_client_id = Random.new.rand(0..99999999999)
= socky :client_id => random_client_id, 
        :channels => channel; 
:javascript
  var user = window.user = #{random_client_id};
= javascript_include_tag "soundcloud.player.api", "listen"

:javascript
  soundcloud.addEventListener('onPlayerReady', function(player, data) {
    var player = window.player = soundcloud.getPlayer('scPlayer');
  });

%object(id="scPlayer" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000")
  %param(name="movie" value="http://player.soundcloud.com/player.swf?url=http%3A%2F%2Fsoundcloud.com%2F#{@userpermalink}%2F#{@trackpermalink}&amp;enable_api=true&amp;object_id=scPlayer")
  %param(name="allowscriptaccess" value="always")
  %embed(id="scPlayerEmbed" allowscriptaccess="always" src="http://player.soundcloud.com/player.swf?url=http%3A%2F%2Fsoundcloud.com%2F#{@userpermalink}%2F#{@trackpermalink}&amp;enable_api=true&amp;object_id=scPlayer" type="application/x-shockwave-flash" name="scPlayer")/

#header
  %a#logo{:href => '/'}
#player-placeholder
#chat-box 
  #enter-username
    %p Enter a username for the chat please:
    %input{:type => "text", :id => "username"}
  #chat
    #messages_container
      %ul#messages
    %input{:type => "text", :id => "send_message"}
    %input{:type => "submit", :value => "Send Message", :id => "send_message_button"}

app/views/socky/login_message.html.haml
%li User #{user} logged in

app/views/socky/message.html.haml
%li
  %span #{current_user}: #{message}